name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #push:
  #  tags: ['0.*']

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: cargo do build
        run: |
          cd herokuru_get
          rustup target add ${{matrix.target}}
          cargo build --release --target x86_64-unknown-linux-musl --bins
          cd -
      - name: check location
        run: |
          ls -l target/release/