name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #push:
  #  tags: ['0.*']

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{matrix.target}}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --release --target ${{matrix.target}}
      - name: check location
        run: |
          ls -l target/release/